### ISSUE TITLE
[Request] Show map name and author name upon starting a map

### ISSUE THREAD

**Issue by eqagunn** [Tekkish/LevelInfo#1]
Hi. Would it be possible to add an option to show map name and author name briefly at the top half of the screen upon starting a map?

The way Doom CE does it:
![0HJHkoW 1](https://github.com/Tekkish/LevelInfo/assets/25494031/c1cfa3a5-63df-4c3e-b04a-6e02cb6aa084)

Info on how to get the data:
https://zdoom.org/wiki/Structs:LevelLocals#:~:text=ReadOnly%20String%20LevelName
https://zdoom.org/wiki/Structs:LevelLocals#:~:text=ReadOnly%20String%20AuthorName

EDIT:
There are two other mods that provide this feature:
https://marisakirisa.me/tmp/ds_maptitle_m.pk3
https://github.com/jekyllgrim/MapNamePrint

Regardless, I believe this feature would suit your mod nicely.

**Comment by Tekkish** [comment]
This has been added in the latest version with the usual series of options to customize it. I've also noticed during testing that very few maps actually use the GZDoom author functionality, so LevelInfo will also attempt to grab author information from maps that include it in their level names.

Thanks for the suggestion.

**Comment by eqagunn** [comment]
Thanks for adding it in! Made a quick test and author detection in Doom 64 CE isn't working properly:
![9Noceut 1](https://github.com/Tekkish/LevelInfo/assets/25494031/30e294df-a26f-4366-9f16-ea977c7cec4f)

Mod options that would be great to have:
- Name Delay
- Show Map Number: Never / Always / Not for hubs
- Scaling Override: Use default scale / 1 / 2 / 3 / 4 / 5 / 6 / 7 / 8

Also, there is a hardcoded 1 second delay. Would be nice to get a control over it via Name Delay and Author Delay.

**Comment by Tekkish** [comment]
It should now work properly. I've also implemented most of your additional suggestions.

**Comment by eqagunn** [comment]
They work great! Some additional feedback:
- Hold Time in Seconds is hardcoded to 5 minimum, even when set to less via INI. A minimum of 3 seconds would be appreciated.
- With LevelInfo positioned at the bottom collecting [powerups will make K/S/T jump up](https://i.imgur.com/C6vnBRu.png). Option to display powerups above K/S/T would solve this.
- I would love to be able to rearrange K/S/T into T/K/S, to make it reflect [the way Raze does it](https://i.imgur.com/ohqDTaK.png).

**Comment by Tekkish** [comment]
The hold time has been reduced to 3 seconds in the latest version. This will automatically disable the name flash. As for your other suggestions - I'm just not really looking to mess with the ordering of stuff.

**Comment by eqagunn** [comment]
Got another one for you! We are given an option of using either Doom font or your font and both of them are equal in size to the default one which is good. Some wads instead of using default graphics and fonts come with their own, and unfortunately their own are often smaller. For such cases LevelInfo appears larger then the rest of HUD.

![Po2rcVf 1](https://github.com/Tekkish/LevelInfo/assets/25494031/f06e7896-e613-4f96-91d9-90f87550bb5f)

The solution would be an option to use SMALLFONT. Additionally, Text Scaling option from Map Name part could be made available under Level Info part.

EDIT:
Encountered a bug in Hands of Necromancy where dispelling Stone Breaker Transformation would remove LevelInfo from the screen for that save. See video demonstration: https://youtu.be/ka3aFBuMCOk Dispelling can be done on-demand or by walking through a portal and it removes LevelInfo in both cases. However, the interesting thing is that this happened only upon  the second dispelling. First time around LevelInfo stayed on screen.

**Comment by Tekkish** [comment]
LevelInfo uses custom fonts for its positioning and alignment. Changing it to use SMALLFONT would cause all sorts of problems. It was my way of getting around HudMessage's limitations at the time. The same applies to the way it's scaled. It uses the UI scaling setting first, then the text scaling override (if applicable).

This scaling can be changed to the method used for the name pop-up, but it would require a bit of reworking. I'm not looking to change that right now, but I may come back to it in the future.

Speaking of reworking, the bug you found forced me to move most of the code that gets values to ZScript. Since I had to do this for every add-on, there's a good chance I overlooked something. If you stumble across any further weird behavior, please let me know.
